config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'memos#index'
   resources :memos, except: :show

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/memo.rb
class Memo < ApplicationRecord

  belongs_to :user

  has_many   :reviews

end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :user
  belongs_to :memo

  validates :body, presence: true
  validates :rate, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :memos

  has_many :reviews

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def hello
    render 'layouts/application.html.erb'
  end

  private
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys:[:name])
    end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController

  before_action :set_memo, only: %i( edit update destroy)

  def index
    @memos = Memo.all
  end

  def new
    @memo = Memo.new
  end

  def create
    @memo = current_user.memos.create(memo_params)
    if @memo.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update

    if @memo.update(memo_params)
      redirect_to root_path(@memo), notice: "success!!!!"
    else
      flash[:alert] = "Error"
      render :edit
    end

  end

  def destroy
    if @memo.user_id == current_user.id
      @memo.destroy
      redirect_to root_path, notice: "DELETE DONE!!!"
    end
  end


  private

  def memo_params
    params.require(:memo).permit(:body,
                                 :people)
  end

  def set_memo
    @memo = Memo.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash_message.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <div >
    <h1><a href="/">Metyou</a></h1>
      <% if user_signed_in? %>
       <div >
         <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
       </div>
      <% else %>
        <div >
         <%= link_to "Log In", new_user_session_path %>
         <%= link_to "Sign Up", new_user_registration_path %>
        </div>
      <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <%= render 'layouts/common/head' %>

  <body>

  <%= render 'layouts/common/flash_message' %>
  <%= render 'layouts/common/header' %>

    <%= yield %>

  </body>
</html>

app/views/layouts/common/_head.html.erb
 <head>
  <title>Metyou</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

app/views/layouts/common/_header.html.erb
<header>
  <div >
    <h1><a href="/">Metyou</a></h1>
      <% if user_signed_in? %>
       <div >
         <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
         <%= link_to "TWEET", new_memo_path, method: :get %>
       </div>
      <% else %>
        <div >
         <%= link_to "Log In", new_user_session_path %>
         <%= link_to "Sign Up", new_user_registration_path %>
        </div>
      <% end %>
  </div>
</header>

app/views/memos/_form.html.erb
<%= form_for memo do |f| %>
  <div>
    <%= f.label :body %><br />
    <%= f.text_field :body, placefolder: "What do you think?" %>
  </div>

  <div>
    <%= f.label :people %><br />
    <%= f.text_field :people, placefolder: "Who does the people look like?" %>
  </div>

  <div>
   <%= f.hidden_field :user_id %>
  </div>

   <div>
    <%= f.submit "Send " %>
   </div>

<% end %>

app/views/memos/_memo.html.erb
<%= memo.body %>
<%= memo.people %>

<%= link_to "EDIT", edit_memo_path(memo), method: :get %>
<%= link_to "DESTROY", "/memos/#{memo.id}", method: :delete %>

app/views/memos/edit.html.erb
<%= render partial: 'form', locals: {memo: @memo} %>

app/views/memos/index.html.erb
<div>
  <% @memos.each do |memo| %>
    <%= render @memos %>
    <% end %>
</div>

app/views/memos/new.html.erb
<%= render partial: 'form', locals: {memo: @memo} %>

app/views/users/edit.html.erb
edit.html.erb